[package]
name = "mfem-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.27.0"
cxx = "1.0"
ctor = "0.2.9"

[build-dependencies]
cmake = "0.1"
autocxx-build = "0.27.0"
semver = "1.0.22"
eyre = "0.6.12"
